version: '3.1'

services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: db_user
      POSTGRES_DB: base_dev
    ports:
     - 5432:5432
    volumes:
      - /var/lib/pg-data